[package]
name = "MemezSwap"
edition = "2024.beta"
license = "MIT"
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
SuiTears = { git = "https://github.com/interest-protocol/suitears.git", subdir = "contracts", rev = "develop" }
MemezV2Invariant = { git = "https://github.com/interest-protocol/memez-v2-invariant.git", rev = "main" }

[addresses]
amm = "0x0"
std = "0x1"
sui = "0x2"
